package com.jundger.work.pojo;

import java.util.Date;

public class Storage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.purchase_duration
     *
     * @mbggenerated
     */
    private Integer purchaseDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.begin_time
     *
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.final_duration
     *
     * @mbggenerated
     */
    private Integer finalDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.terminal_id
     *
     * @mbggenerated
     */
    private Integer terminalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.cell_id
     *
     * @mbggenerated
     */
    private Integer cellId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.order_status
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.pay_status
     *
     * @mbggenerated
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.keyt
     *
     * @mbggenerated
     */
    private String keyt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage_service.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_service
     *
     * @mbggenerated
     */
    public Storage(Integer id, String orderNo, Integer purchaseDuration, Date createTime, Date beginTime, Date endTime, Integer finalDuration, Integer terminalId, Integer cellId, String orderStatus, String payStatus, Integer userId, String keyt, String detail) {
        this.id = id;
        this.orderNo = orderNo;
        this.purchaseDuration = purchaseDuration;
        this.createTime = createTime;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.finalDuration = finalDuration;
        this.terminalId = terminalId;
        this.cellId = cellId;
        this.orderStatus = orderStatus;
        this.payStatus = payStatus;
        this.userId = userId;
        this.keyt = keyt;
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_service
     *
     * @mbggenerated
     */
    public Storage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.id
     *
     * @return the value of storage_service.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.id
     *
     * @param id the value for storage_service.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.order_no
     *
     * @return the value of storage_service.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.order_no
     *
     * @param orderNo the value for storage_service.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.purchase_duration
     *
     * @return the value of storage_service.purchase_duration
     *
     * @mbggenerated
     */
    public Integer getPurchaseDuration() {
        return purchaseDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.purchase_duration
     *
     * @param purchaseDuration the value for storage_service.purchase_duration
     *
     * @mbggenerated
     */
    public void setPurchaseDuration(Integer purchaseDuration) {
        this.purchaseDuration = purchaseDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.create_time
     *
     * @return the value of storage_service.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.create_time
     *
     * @param createTime the value for storage_service.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.begin_time
     *
     * @return the value of storage_service.begin_time
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.begin_time
     *
     * @param beginTime the value for storage_service.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.end_time
     *
     * @return the value of storage_service.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.end_time
     *
     * @param endTime the value for storage_service.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.final_duration
     *
     * @return the value of storage_service.final_duration
     *
     * @mbggenerated
     */
    public Integer getFinalDuration() {
        return finalDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.final_duration
     *
     * @param finalDuration the value for storage_service.final_duration
     *
     * @mbggenerated
     */
    public void setFinalDuration(Integer finalDuration) {
        this.finalDuration = finalDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.terminal_id
     *
     * @return the value of storage_service.terminal_id
     *
     * @mbggenerated
     */
    public Integer getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.terminal_id
     *
     * @param terminalId the value for storage_service.terminal_id
     *
     * @mbggenerated
     */
    public void setTerminalId(Integer terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.cell_id
     *
     * @return the value of storage_service.cell_id
     *
     * @mbggenerated
     */
    public Integer getCellId() {
        return cellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.cell_id
     *
     * @param cellId the value for storage_service.cell_id
     *
     * @mbggenerated
     */
    public void setCellId(Integer cellId) {
        this.cellId = cellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.order_status
     *
     * @return the value of storage_service.order_status
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.order_status
     *
     * @param orderStatus the value for storage_service.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.pay_status
     *
     * @return the value of storage_service.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.pay_status
     *
     * @param payStatus the value for storage_service.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.user_id
     *
     * @return the value of storage_service.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.user_id
     *
     * @param userId the value for storage_service.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.keyt
     *
     * @return the value of storage_service.keyt
     *
     * @mbggenerated
     */
    public String getKeyt() {
        return keyt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.keyt
     *
     * @param keyt the value for storage_service.keyt
     *
     * @mbggenerated
     */
    public void setKeyt(String keyt) {
        this.keyt = keyt == null ? null : keyt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage_service.detail
     *
     * @return the value of storage_service.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage_service.detail
     *
     * @param detail the value for storage_service.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}