package com.jundger.work.pojo;

public class Terminal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.zone
     *
     * @mbggenerated
     */
    private String zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.reserves
     *
     * @mbggenerated
     */
    private Integer reserves;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.storage_amount
     *
     * @mbggenerated
     */
    private Integer storageAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.borrow_amount
     *
     * @mbggenerated
     */
    private Integer borrowAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.idle_storage
     *
     * @mbggenerated
     */
    private Integer idleStorage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.idle_borrow
     *
     * @mbggenerated
     */
    private Integer idleBorrow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.adress
     *
     * @mbggenerated
     */
    private String adress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    public Terminal(Integer id, String zone, Integer reserves, Integer storageAmount, Integer borrowAmount, Integer idleStorage, Integer idleBorrow, String adress, String longitude, String latitude, String detail) {
        this.id = id;
        this.zone = zone;
        this.reserves = reserves;
        this.storageAmount = storageAmount;
        this.borrowAmount = borrowAmount;
        this.idleStorage = idleStorage;
        this.idleBorrow = idleBorrow;
        this.adress = adress;
        this.longitude = longitude;
        this.latitude = latitude;
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    public Terminal() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.id
     *
     * @return the value of terminal.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.id
     *
     * @param id the value for terminal.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.zone
     *
     * @return the value of terminal.zone
     *
     * @mbggenerated
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.zone
     *
     * @param zone the value for terminal.zone
     *
     * @mbggenerated
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.reserves
     *
     * @return the value of terminal.reserves
     *
     * @mbggenerated
     */
    public Integer getReserves() {
        return reserves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.reserves
     *
     * @param reserves the value for terminal.reserves
     *
     * @mbggenerated
     */
    public void setReserves(Integer reserves) {
        this.reserves = reserves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.storage_amount
     *
     * @return the value of terminal.storage_amount
     *
     * @mbggenerated
     */
    public Integer getStorageAmount() {
        return storageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.storage_amount
     *
     * @param storageAmount the value for terminal.storage_amount
     *
     * @mbggenerated
     */
    public void setStorageAmount(Integer storageAmount) {
        this.storageAmount = storageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.borrow_amount
     *
     * @return the value of terminal.borrow_amount
     *
     * @mbggenerated
     */
    public Integer getBorrowAmount() {
        return borrowAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.borrow_amount
     *
     * @param borrowAmount the value for terminal.borrow_amount
     *
     * @mbggenerated
     */
    public void setBorrowAmount(Integer borrowAmount) {
        this.borrowAmount = borrowAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.idle_storage
     *
     * @return the value of terminal.idle_storage
     *
     * @mbggenerated
     */
    public Integer getIdleStorage() {
        return idleStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.idle_storage
     *
     * @param idleStorage the value for terminal.idle_storage
     *
     * @mbggenerated
     */
    public void setIdleStorage(Integer idleStorage) {
        this.idleStorage = idleStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.idle_borrow
     *
     * @return the value of terminal.idle_borrow
     *
     * @mbggenerated
     */
    public Integer getIdleBorrow() {
        return idleBorrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.idle_borrow
     *
     * @param idleBorrow the value for terminal.idle_borrow
     *
     * @mbggenerated
     */
    public void setIdleBorrow(Integer idleBorrow) {
        this.idleBorrow = idleBorrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.adress
     *
     * @return the value of terminal.adress
     *
     * @mbggenerated
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.adress
     *
     * @param adress the value for terminal.adress
     *
     * @mbggenerated
     */
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.longitude
     *
     * @return the value of terminal.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.longitude
     *
     * @param longitude the value for terminal.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.latitude
     *
     * @return the value of terminal.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.latitude
     *
     * @param latitude the value for terminal.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.detail
     *
     * @return the value of terminal.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.detail
     *
     * @param detail the value for terminal.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}