package com.jundger.work.pojo;

public class Terminal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.zone
     *
     * @mbggenerated
     */
    private String zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.reserves
     *
     * @mbggenerated
     */
    private Integer reserves;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.storage_amount
     *
     * @mbggenerated
     */
    private Integer storageAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.borrow_amount
     *
     * @mbggenerated
     */
    private Integer borrowAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.spare_count
     *
     * @mbggenerated
     */
    private Integer spareCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    public Terminal(Integer id, String zone, Integer reserves, Integer storageAmount, Integer borrowAmount, Integer spareCount, String position, String detail) {
        this.id = id;
        this.zone = zone;
        this.reserves = reserves;
        this.storageAmount = storageAmount;
        this.borrowAmount = borrowAmount;
        this.spareCount = spareCount;
        this.position = position;
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    public Terminal() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.id
     *
     * @return the value of terminal.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.id
     *
     * @param id the value for terminal.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.zone
     *
     * @return the value of terminal.zone
     *
     * @mbggenerated
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.zone
     *
     * @param zone the value for terminal.zone
     *
     * @mbggenerated
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.reserves
     *
     * @return the value of terminal.reserves
     *
     * @mbggenerated
     */
    public Integer getReserves() {
        return reserves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.reserves
     *
     * @param reserves the value for terminal.reserves
     *
     * @mbggenerated
     */
    public void setReserves(Integer reserves) {
        this.reserves = reserves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.storage_amount
     *
     * @return the value of terminal.storage_amount
     *
     * @mbggenerated
     */
    public Integer getStorageAmount() {
        return storageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.storage_amount
     *
     * @param storageAmount the value for terminal.storage_amount
     *
     * @mbggenerated
     */
    public void setStorageAmount(Integer storageAmount) {
        this.storageAmount = storageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.borrow_amount
     *
     * @return the value of terminal.borrow_amount
     *
     * @mbggenerated
     */
    public Integer getBorrowAmount() {
        return borrowAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.borrow_amount
     *
     * @param borrowAmount the value for terminal.borrow_amount
     *
     * @mbggenerated
     */
    public void setBorrowAmount(Integer borrowAmount) {
        this.borrowAmount = borrowAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.spare_count
     *
     * @return the value of terminal.spare_count
     *
     * @mbggenerated
     */
    public Integer getSpareCount() {
        return spareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.spare_count
     *
     * @param spareCount the value for terminal.spare_count
     *
     * @mbggenerated
     */
    public void setSpareCount(Integer spareCount) {
        this.spareCount = spareCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.position
     *
     * @return the value of terminal.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.position
     *
     * @param position the value for terminal.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal.detail
     *
     * @return the value of terminal.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal.detail
     *
     * @param detail the value for terminal.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}