package com.jundger.work.dao;

import com.jundger.work.pojo.Cell;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cell
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cell
     *
     * @mbggenerated
     */
    int insert(Cell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cell
     *
     * @mbggenerated
     */
    int insertSelective(Cell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cell
     *
     * @mbggenerated
     */
    Cell selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cell
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cell
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cell record);

    Cell selectAvailableCell(@Param("terminal_id") Integer terminal_id, @Param("type") String type);
}