package com.jundger.work.dao;

import com.jundger.work.pojo.Storage;
import org.apache.ibatis.annotations.Param;

public interface StorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_service
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_service
     *
     * @mbggenerated
     */
    int insert(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_service
     *
     * @mbggenerated
     */
    int insertSelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_service
     *
     * @mbggenerated
     */
    Storage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_service
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage_service
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Storage record);

    Storage selectOrderByUserId(Integer id);

    Storage selectRunningOrderByUserId(Integer id);

    Storage selectByOrderNo(String order_no);

    int resetOvertimeOrder(String order_no);

    int resetExpireOrder(String order_no);

    Storage selectOrderForCheck(@Param("order_no") String order_no, @Param("keyt") String keyt, @Param("terminal_id") Integer terminal_id);

    int updateBeginStatus(String order_no);
}