package com.jundger.work.dao;

import com.jundger.work.pojo.Terminal;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    int insert(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    int insertSelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    Terminal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Terminal record);

    List<Terminal> selectAll();

    List<Map<String, Object>> selectNear(@Param("longitude") Float longitude, @Param("latitude") Float latitude, @Param("radius") Double radius);

}