package com.jundger.work.dao;

import com.jundger.work.pojo.Terminal;

public interface TerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    int insert(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    int insertSelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    Terminal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Terminal record);
}